baseURL = "https://geodistributed.systems/"
languageCode = "en-us"
title = "Geo-Distributed Systems"
theme = "learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"