baseURL = "https://geodistributed.systems/"
theme = "learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

  # A title is set by default when you use a shortcut in the menu. Use this setting to hide it.
  disableShortcutsTitle = true

  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false

  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true

  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true

  # Disable search function. It will hide search bar
  disableSearch = false

  # Description of the site, will be used in meta information
  description = "landing page for Rotational Labs educational content on globally distributed systems"

# English is the default language
defaultContentLanguage = "en"

# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= false

[Languages]
[Languages.en]
title = "Geo-Distributed Systems"
weight = 10
languageName = "English"

[Languages.fr]
title = "Systèmes Géo-Distribués"
weight = 11
languageName = "Français"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false
